### ISSUE TITLE
[BUG] nodes_over_time not working

### ISSUE THREAD

**Issue by szyszyzys** [fpour/TGX#44]
Hello, 

I started working on TGNN recently and found this repo very useful!

I installed TGX from and not sure if the bug has been fixed in the latest release.

I am trying to use nodes_over_time on tgbl-flight dataset and got this error.
![image](https://github.com/ComplexData-MILA/TGX/assets/87307087/f5bd27f7-7112-48c4-ac0f-df9cd0a23cc2)
From dtdg.data.keys() we can see that it is because how discretize_edges works, the key of the dtdg.data is not necessary start from 0.
![image](https://github.com/ComplexData-MILA/TGX/assets/87307087/e90432be-cd6f-4724-b776-f5bbf2fa4764)

![image](https://github.com/ComplexData-MILA/TGX/assets/87307087/b9b0d8e2-8f1f-4c9b-a166-d51d3489b04a)

BTW, is there any function that turn a snapshot of temporal graphs into the the form of PYG Data object? Want to see static GNNs' performance on these dynamic datasets.

**Comment by shenyangHuang** [comment]
Hi, 

Thanks for your interest in our work and reporting this issue. 
did you load `dtdg` graph from your own dataset? did you obtain it by [`tgx.Graph.discretize`](https://github.com/ComplexData-MILA/TGX/blob/master/tgx/classes/graph.py) function? If not, you can see our [tutorial on how to load dataset](https://github.com/ComplexData-MILA/TGX/blob/master/docs/tutorials/data_loader.ipynb). 

The plotting function requires the snapshots to start from 0 and then increment 1 by 1, in addition, there should be no gaps in the timestamps. A simple solution for your issue above is to remap the integers to start from 0. I have wrote a helper function in [`tgx.Graph.shift_time_to_zero`](https://github.com/ComplexData-MILA/TGX/blob/master/tgx/classes/graph.py) which will remap the snapshot ids to start from `0`.

For your second question. it is non-trivial to turn a temporal graph into a static graph in PyG because edges can exist in multiple snapshots, nodes are different at each snapshot etc. What you can do however, is to construct [`TemporalData`](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/data/temporal.html) object in PyG. 

You can achieves this quite easily by converting `numpy` array into torch `tensor` and then construct `TemporalData`. You can get the `numpy` array by using [`tgx.Graph.export_full_data`](https://github.com/ComplexData-MILA/TGX/blob/master/tgx/classes/graph.py). 
```
data = TemporalData(
            src=src,
            dst=dst,
            t=ts,
        )
```

Best,
Andy

**Comment by szyszyzys** [comment]
Thanks for the response!

**Comment by shenyangHuang** [comment]
issue closed
